### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by fjgauthier** [trustly/trustly-client-python#4] opened 2017-02-01 17:11 UTC
Hello, is it possible to draft a release?

As of right now, there are no tags or releases.

While we are in development/testing, this is has no impact to us, but for production systems, we would prefer to install a fixed version instead of grabbing what flavor of master currently has.

Thanks!

**Comment by underyx** [comment] 2017-02-09 12:10
:+1:, we're currently forced to commit the library in a `vendor/` directory, which makes our release process way more complicated than it should be.

**Comment by fjgauthier** [comment] 2017-02-09 14:43
Thanks.  I understand.

**Comment by Pelleplutt** [comment] 2017-02-09 15:24
We have not planned to do any releases of this code as it is an example implementation of the API in Python. Feel free to use it as is, but the intended use is as an example. Not a released product.

**Comment by underyx** [comment] 2017-04-04 08:14
@Pelleplutt So what if I just forked the client and published it myself to https://pypi.python.org/pypi/trustly?

**Comment by Pelleplutt** [comment] 2017-04-04 08:30
@underyx as the code is licensed under MIT I cannot technically prevent you from doing this. HOWEVER please read my previous response to this. This is not code intended to be released as a drop-in ready to use module for Trustly integration. This is an example implementation of the API in Python. Intended use of this is a technical reference on how an implementation can be done. This might change in the future, if and when that happens we will need to provide a better baseline in terms of testing and release cycle of this code.
Please do not enforce your internal release problems with a repository on github that has nothing to do with it. If this is a problem in our own build then perhaps addressing what makes that complicated would be a better way to go.

**Comment by underyx** [comment] 2017-04-04 08:38
While you're describing this repo as an unstable reference implementation, we've been using it in production for a long time with no issues. I bet you that most people who would implement a trustly client would end up with way more unstable and buggy code.

We're also obviously not going to be the only ones who would benefit from this code being on PyPI.

Or, to refer to [the Zen of Python](https://www.python.org/dev/peps/pep-0020/):

> practicality beats purity

There's no arguing that having this 'impure' package published on PyPI would be practical for people.

I offered to publish it under my name to relieve Trustly from the responsibility of maintaining the package. Naturally, I would do my best to inform people of the unstable status of the project. Perhaps you would be (personally) okay with a different package name? `trustly-reference` maybe?

**Closed by underyx** 2017-04-04 08:38 UTC

**Comment by Pelleplutt** [comment] 2017-04-04 08:46
Our intent is never to publish untested or unstable code. I am glad it works as intended. My point being that if this would be an official Trustly released package we would need to maintain it as such. 

I appreciate the effort, thanks. But no thanks. Having an unofficial package maintained by a third party copying the actual product does not really add value or practicality as I see it. The best source of a published package that is originally written and maintained by us would be the original author. This would confuse and complicate.

Adress the issues in your build instead.

**Comment by underyx** [comment] 2017-04-04 08:59
Alright, I will not publish it then. I still would like to point out that

>Adress the issues in your build instead

is not a resolution here, since the problem I'm describing is exactly that this is creating an issue that needs to be addressed — we can't install this one dependency the same way as all the other ones, since all our other dependencies are on pypi and this one is not. The expected behavior would be keeping our build process simple and consistent, with no special cases.
